Create table encuesta_mandos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    servicio text,
    ayuda2 text,
    ayuda3 text,
    ayuda4 text,
    ayuda5 text,
    ayuda6 text,
    ayuda7 text,
    ayuda8 text,
    ayuda9 text,
    ayuda10 text,
    ayuda11 text,
    ayuda12 text,
    ayuda13 text,
    ayuda14 text,
    ayuda15 text,
    ayuda16 text,
    opiniones varchar(500)
);