create table Cuestionario_satisfaccion(
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nombre varchar(100),
    pregunta1 varchar(100),
    pregunta2 varchar(100),
    pregunta3 varchar(100),
    pregunta4 varchar(100),
    pregunta5 varchar(100),
    pregunta6 varchar(100),
    pregunta7 varchar(100),
    pregunta8 varchar(100),
    pregunta9 varchar(100),
    pregunta10 varchar(100),
    pregunta11 varchar(100),
    pregunta12 varchar(100),
    pregunta13 varchar(100),
    pregunta14 varchar(100),
    pregunta15 varchar(100),
    opiniones varchar(500),
    pregunta16 text,observaciones_pregunta16 varchar(500),
    pregunta17 text,observaciones_pregunta17 varchar(500),
    pregunta18 text,observaciones_pregunta18 varchar(500),
    pregunta19 text,observaciones_pregunta19 varchar(500),
    pregunta20 text,observaciones_pregunta20 varchar(500),
    pregunta21 text,observaciones_pregunta21 varchar(500),
    pregunta22 text,observaciones_pregunta22 varchar(500),
    pregunta23  text,observaciones_pregunta23 varchar(500),
    pregunta24 text,observaciones_pregunta24 varchar(500),
    pregunta25 text,observaciones_pregunta25 varchar(500),
    pregunta26 text,observaciones_pregunta26 varchar(500),
    pregunta27 text,observaciones_pregunta27 varchar(500),
    pregunta28 text,observaciones_pregunta28 varchar(500),
    pregunta29 text,observaciones_pregunta29 varchar(500),
    pregunta30 text,observaciones_pregunta30 varchar(500),
    pregunta31 text,observaciones_pregunta31 varchar(500),
    pregunta32 text,observaciones_pregunta32 varchar(500),
    pregunta33 text,observaciones_pregunta33 varchar(500),
    pregunta34 text,observaciones_pregunta34 varchar(500),
    opiniones1 varchar(300)
);

CREATE TABLE CuestionarioSatisfaccion (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nombre VARCHAR(100),
    pregunta1 INT,
    pregunta2 INT,
    pregunta3 INT,
    pregunta4 INT,
    pregunta5 INT,
    pregunta6 INT,
    pregunta7 INT,
    pregunta8 INT,
    pregunta9 INT,
    pregunta10 INT,
    pregunta11 INT,
    pregunta12 INT,
    pregunta13 INT,
    pregunta14 INT,
    pregunta15 INT,
    observaciones1 TEXT,
    pregunta16 INT,
    observaciones2 TEXT,
    pregunta17 INT,
    observaciones3 TEXT,
    pregunta18 INT,
    observaciones4 TEXT,
    pregunta19 INT,
    observaciones5 TEXT,
    pregunta20 INT,
    observaciones6 TEXT,
    pregunta21 INT,
    observaciones7 TEXT,
    pregunta22 INT,
    observaciones8 TEXT,
    pregunta23 INT,
    observaciones9 TEXT,
    pregunta24 INT,
    observaciones10 TEXT,
    pregunta25 INT,
    observaciones11 TEXT,
    pregunta26 INT,
    observaciones12 TEXT,
    pregunta27 INT,
    observaciones13 TEXT,
    pregunta28 INT,
    observaciones14 TEXT,
    pregunta29 INT,
    observaciones15 TEXT,
    pregunta30 INT,
    observaciones16 TEXT,
    opiniones TEXT
);
